apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx-clusterrole-nisa-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ingress-nginx  # Ensure this matches your service account namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
