apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      containers:
        - name: nginx-ingress-controller
          image: bitnami/nginx-ingress-controller:latest
          ports:
            - containerPort: 80
            - containerPort: 443
      {{- if .Values.autoscaling.enabled }}
      autoscale:
        minReplicas: {{ .Values.autoscaling.minReplicas }}
        maxReplicas: {{ .Values.autoscaling.maxReplicas }}
        targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
      {{- end }}
      serviceAccountName: nginx-ingress-service-account
