apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-chart-mahi.fullname" . }}
spec:
  rules:
    - host: nginx.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-ingress-service
                port:
                  number: 80


